services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=weather
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres